### PR TITLE
added uml diagram for eduhub

### PR DESCRIPTION
**Pull request by ChiragShukla222**

### CODE REVIEW

**Review by siddharthisrani — APPROVED** [review]
Excellent work on the UML diagram! It clearly and effectively illustrates the system architecture and interactions. The details are well-organized and the visual representation enhances our understanding of the design.

**Review by Yashop181 — APPROVED** [review]
Great work on the UML diagram for EduHub! It's really well-done and clean. Keep up the excellent work!

**Review by shivansh84ya — COMMENTED** [review]
Everything looks good, and I am approving the PR.

**Review by shivansh84ya — APPROVED** [review]
Everything looks good, and I am approving the PR.

**Pull request merged**
