### PR TITLE
Added connection of mongodb

### PR DESCRIPTION
**Pull request by siddharthisrani**
Created Database Connection with MongoDb

### CODE REVIEW

**Review by shivansh84ya — APPROVED** [review]
All looks good, approving for merge

**Review by Yashop181 — APPROVED** [review]

**Comment by shivansh84ya** [comment]
@FullStackWebDeveloper-HARSH everything looks good, Accept this PR

**Comment by shivansh84ya** [comment]
@FullStackWebDeveloper-HARSH As everything looks good, Accept this PR

**Review by ChiragShukla222 — APPROVED** [review]
please add comments also for functions

**Pull request merged**
